// <auto-generated />
using System;
using Inventory.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.API.Migrations
{
    [DbContext(typeof(SqliteInventoryDbContext))]
    [Migration("20210307170452_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Inventory.API.Models.InventoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfInventory")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductDefinitionId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Inventory.API.Models.ProductDefinitionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<long>("CompanyPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemReference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductDefinitions");
                });

            modelBuilder.Entity("Inventory.API.Models.InventoryModel", b =>
                {
                    b.HasOne("Inventory.API.Models.ProductDefinitionModel", "ProductDefinition")
                        .WithMany("InventoryModels")
                        .HasForeignKey("ProductDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDefinition");
                });

            modelBuilder.Entity("Inventory.API.Models.ProductDefinitionModel", b =>
                {
                    b.Navigation("InventoryModels");
                });
#pragma warning restore 612, 618
        }
    }
}
